<div class="main">
    <section class="section">
        <img src="<?php echo UPLOAD_DIR . '\\' . $pageData['image']['filename']?>"> 
        <h2 class='section-item'>
            <?php echo $pageData['image']['title']?>
        </h2>
    </section>
    <div class="section-item">
        <h2 class=''>
            Автор: переменная Оставлен: переменная <br> Коммент: Тут будет коммент. 
        </h2>
    </div>
    <div class="comment">
        <form action="comment" method="post">
            <input type="hidden" name="act" value="">
            <input type="hidden" name="pid" value="">
            <input type="hidden" name="id" value="">
            <label for="comment">Комментарий:</label>
            <input name="comment" rows="4" cols="50" placeholder="..." class="input" value="" required autofocus>
            <input name="submit" type="submit" value="Оставить Комментарий" class="button">
        </form>
    </div>
</div>