<div class="main">
    <section class="section">
        <img src="/uploads/Кот_011.jpg"> 
        <h2 class='section-item'>
            Тут будет описание картинки типо текст арии, Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi, atque cum? Assumenda dolorum beatae in! Quos, voluptatibus. Ut iure voluptatibus perspiciatis soluta provident. Ratione odit fugiat harum magnam eligendi earum.
        </h2>
    </section>
    <div class="section-item">
        <h2 class=''>
            Автор: переменная Оставлен: переменная <br> Коммент: Тут будет коммент. 
        </h2>
    </div>
    <div class="comment">
        <form action="comment" method="post">
            <input type="hidden" name="act" value="">
            <input type="hidden" name="pid" value="">
            <input type="hidden" name="id" value="">
            <label for="comment">Комментарий:</label>
            <input name="comment" rows="4" cols="50" placeholder="..." class="input" value="" required autofocus>
            <input name="submit" type="submit" value="Оставить Комментарий" class="button">
        </form>
    </div>
</div>