<main class="form main">
    <form method="post">
         <label for="login">Имя пользователя:</label>
         <input name="username" type="text" placeholder="..." required autofocus>
         <label for="password">Пароль:</label>
         <input name="password" type="password" placeholder="..." required>
         <input class="button" type="submit" value="Войти">
        <p>
            У вас нет аккаунта? - <a class="res" href="register">Зарегестрируйтесь</a>!
        </p>
        <?php 
            if(!empty($pageData['error'])){
                echo "<p class='msg'>" . $pageData['error'] . "</p>";
            }
        ?>
    </form>
</main>