    <main class="main">
        <section class="section">
            <h2 class='section-item'>
                Тут будет описание картинки типо текст арии, Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi, atque cum? Assumenda dolorum beatae in! Quos, voluptatibus. Ut iure voluptatibus perspiciatis soluta provident. Ratione odit fugiat harum magnam eligendi earum.
            </h2>
            <img src="/uploads/Кот_011.jpg">
        </section>
        <section class="section">
            <h2 class='section-item'>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta quas nam tenetur omnis non vitae dolores architecto temporibus assumenda ullam sit repellat aperiam nisi sed, magnam sunt exercitationem est ad.
            </h2>
            <img src="/uploads/кот_007.jpg">
        </section>
        <section class="section">
            <h2 class='section-item'>
                <Strong>Stone-терапия</Strong> - это массаж теплыми и холодными камнями в лечебных целях. Процедура обладает спазмолитическим, седативным, адаптогенным, болеутоляющим, ангиотрофическим эффектами. Метод улучшает работу нервной системы, устраняет признаки стресса и переутомления.
                <p> Цена: &#8381</p>
            </h2>
            <img src="/uploads/кот_002.jpg">
        </section>
        <section class="section">
            <h2 class='section-item'>
                <Strong>Массаж</Strong> - это лечебное воздействие на организм через кожу. В массаж входят такие приемы как поглаживание, растирание, разминание, вибрация и похлопывание. Такое воздействие на мышцы раздражает нервные окончания, которые, в свою очередь, посылают импульсы в мозг.
                <p> Цена: &#8381</p>
            </h2>
            <img src="/uploads/кот_003.jpg">
        </section>
        <section class="section">
            <h2 class='section-item'>
                <Strong>Обертывание</Strong> - это косметическая процедура, которая проводится с целью ухода за кожей тела, коррекции фигуры и лечения целлюлита, подразумевающая нанесение на поверхность кожи специализированных составов, оказывающих влияние на микроциркуляцию, лимфоток и обмен веществ.
                <p> Цена: &#8381</p>
            </h2>
            <img src="/uploads/кот_004.jpg">
        </section>
        <section class="section">
            <h2 class='section-item' id="peeling">
                <Strong>Пилинг</Strong> - процедура, воздействующая на эпидермис по всей толщине рогового слоя. Для этой процедуры могут быть использованы традиционные препараты поверхностного пилинга, то есть фруктовые кислоты, однако время их воздействия на кожу лица увеличивают до 30-40 минут.
                <p> Цена: &#8381</p>
            </h2>
            <img src="/uploads/кот_008.jpg">
        </section>
    </main>