<main class="form main">    
    <form method="post" class="login-form" enctype="multipart/form-data">
    <?php if(!empty($_SESSION['user'])) { ?>
    <div>
        Максимальный размер файла: <?php echo MAX_FILE_SIZE / 1000000; ?>Мб.
        Допустимые форматы:<?php echo '<br>' . implode(', ', ALLOWED_TYPES) ?>.            
    </div>
        <input type="hidden" name="MAX_FILE_SIZE" value="<?php echo MAX_FILE_SIZE ?>">
        <label for="files">Выберите фотографии для загрузки:</label>
        <input type="file" name="files[]" multiple required accept=".jpg, .jpeg, .png, .tiff">
        <label for="title">Описание:</label>
        <textarea class="input"name="title" type="text" rows="5" placeholder="Описание картинки" autofocus></textarea>
        <input class="button" name="submit" type="submit" value="Загрузить">
        <?php 
        if (isset($pageData['errors']) && !empty($pageData['errors'])) {
            foreach ($pageData['errors'] as $error) {
            echo "<p class='msg'>" . $error . "</p>";
            }
        }
        } else { ?>
    <div>
        <h2>Что бы загрузить фотографии - <a class="res" href="logon">Авторизируйтесь!</a></h2>           
    </div>
        <?php } ?>
    </form>
</main>